### ISSUE TITLE
traces not show up in jaeger-ui

### ISSUE THREAD

**Issue by wolfelven** [jaegertracing/jaeger-client-cpp#79]
Hello, everyone, my code:
#include <thread>

int main() {
  auto config = jaegertracing::Config(
      false,
      jaegertracing::samplers::Config(jaegertracing::kSamplerTypeConst, 1),
      jaegertracing::reporters::Config(
          jaegertracing::reporters::Config::kDefaultQueueSize,
          std::chrono::seconds(1), true));
  auto tracer = jaegertracing::Tracer::make("wherearemyspans?", config);
  auto span = tracer->StartSpan("abc");
  span->Finish();
  tracer->Close();
  return 0;
}

**Comment by isaachier** [comment]
Please provide more details. What are you running in the UI? What version of the client are you using?

**Comment by wolfelven** [comment]
@isaachier the cpp code version is v0.2.0. In the code above, the span don't show in jaeger's ui.

**Comment by isaachier** [comment]
Please try 0.3.0.

**Comment by wolfelven** [comment]
@isaachier Hi，when i changed to 0.3.0, there are errors when doing make.
/Users/xujie/Desktop/C_Project/jaeger-client-cpp-0.3.0/src/jaegertracing/UDPTransportTest.cpp:45:19: error: 
      no matching constructor for initialization of 'std::system_error'
            throw std::system_error();
                  ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/system_error:625:5: note: 
      candidate constructor not viable: requires single argument '__ec', but no
      arguments were provided
    system_error(error_code __ec);
    ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/system_error:618:24: note: 
      candidate constructor (the implicit copy constructor) not viable: requires
      1 argument, but 0 were provided
class _LIBCPP_TYPE_VIS system_error
                       ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/system_error:623:5: note: 
      candidate constructor not viable: requires 2 arguments, but 0 were
      provided
    system_error(error_code __ec, const string& __what_arg);
    ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/system_error:624:5: note: 
      candidate constructor not viable: requires 2 arguments, but 0 were
      provided
    system_error(error_code __ec, const char* __what_arg);
    ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/system_error:628:5: note: 
      candidate constructor not viable: requires 2 arguments, but 0 were
      provided
    system_error(int __ev, const error_category& __ecat);
    ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/system_error:626:5: note: 
      candidate constructor not viable: requires 3 arguments, but 0 were
      provided
    system_error(int __ev, const error_category& __ecat, const string& _...
    ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/system_error:627:5: note: 
      candidate constructor not viable: requires 3 arguments, but 0 were
      provided
    system_error(int __ev, const error_category& __ecat, const char* __w...
    ^
1 error generated.
make[2]: *** [CMakeFiles/UnitTest.dir/src/jaegertracing/UDPTransportTest.cpp.o] Error 1
make[1]: *** [CMakeFiles/UnitTest.dir/all] Error 2
make: *** [all] Error 2

**Comment by isaachier** [comment]
Yes I'm sorry about that. This compilation error is resolved in the version I am releasing now (0.4.0). If you want to build with 0.3.0, use `-DBUILD_TESTING=OFF` in CMake.
