### ISSUE TITLE
update hunter version to use a newer opentracing-cpp?

### ISSUE THREAD

**Issue by ppggff** [jaegertracing/jaeger-client-cpp#118]
The build-in version hunter will build with opentracing-cpp 1.4.0, and the "plugin so" will return error with other version.

**Comment by isaachier** [comment]
Good catch. Will update now. Thanks.

**Comment by isaachier** [comment]
@rnburn, while doing this, discovered that Jaeger does not implement new OpenTracing dynamic loading function. Where do I use `OPENTRACING_DECLARE_IMPL_FACTORY`? In the implementation file (DynamicLoad.cpp) or in the tracer factory header (TracerFactory.h)?

**Comment by ppggff** [comment]
It would be better to add the version number of corresponding opentracing-cpp with the released binary plugin library file.

**Comment by isaachier** [comment]
Fixed in #120.
